name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
      
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Vercel CLI
        working-directory: src/app/web
        run: npm install --global vercel@latest
        
      - name: Build Project Artifacts
        working-directory: src/app/web
        run: vercel build --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}
        
      - name: Deploy Project Artifacts to Vercel
        working-directory: src/app/web
        run: vercel deploy --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}
